service: candidate-service

provider:
  name: aws
  runtime: nodejs8.10

# you can overwrite defaults here
  stage: dev
  region: eu-west-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${ssm:/${opt:stage, self:provider.stage}/dynamodb/candidates}"
    - Effect: Allow
      Action:
        - ssm:GetParameter
      Resource: "arn:aws:ssm:${self:provider.region}:*:parameter/${opt:stage, self:provider.stage}/dynamodb/candidates"

# you can define service wide environment variables here
  environment:
    stage: ${opt:stage, self:provider.stage}

# you can add packaging information here
package:
  include:
    
  exclude:
    - package-lock.json
    - node_modules/**
  individually: true

functions:
  candidateSubmission:
    handler: api/candidate-submit.execute
    memorySize: 128
    description: Submit candidate information and starts interview process.
    events:
      - http: 
          path: candidates
          method: post
    package:
      exclude:
        - '!node_modules/uuid/**'

  listCandidates:
    handler: api/candidate-list.execute
    memorySize: 128
    description: List all candidates
    events:
      - http:
          path: candidates
          method: get

  getCandidateDetails:
    handler: api/candidate-get.execute
    memorySize: 128
    description: Get specific candidate details
    events:
      - http:
          path: candidates/{id}
          method: get

# you can add CloudFormation resource templates here
# resources:
#   Resources:

#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"

plugins:
  - serverless-offline